apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: argo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: argocd-server
              namespace: argocd
            port: 80
  